# -*- coding: utf-8 -*-
"""protein.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lS7DcxMvatgiDfhYMu6iUhjB7_upB6ci
"""

!pip install requests

import pandas as pd
import requests
from google.colab import files

df = pd.read_csv("protein_synonyms.csv", encoding="latin1")

column_name = df.columns[0]
proteins = df[column_name].dropna().astype(str).unique().tolist()

BASE_URL = "https://rest.uniprot.org/uniprotkb"

results = []

for i, pid in enumerate(proteins, 1):
    print(f"Fetching {i}/{len(proteins)}: {pid}")

    url = f"{BASE_URL}/{pid}.json"
    try:
        r = requests.get(url, timeout=10)

        if r.status_code != 200:
            results.append({
                "UniProtID": pid,
                "ProteinName": None,
                "ProteinSynonyms": None,
                "GeneName": None,
                "GeneSynonyms": None
            })
            continue

        data = r.json()

        prot_name = None
        prot_syn = []
        gene_name = None
        gene_syn = []

        if "proteinDescription" in data:
            pdsc = data["proteinDescription"]

            if "recommendedName" in pdsc:
                prot_name = pdsc["recommendedName"]["fullName"]["value"]

            if "alternativeNames" in pdsc:
                for alt in pdsc["alternativeNames"]:
                    if "fullName" in alt:
                        prot_syn.append(alt["fullName"]["value"])

        if "genes" in data and data["genes"]:
            g = data["genes"][0]
            if "geneName" in g:
                gene_name = g["geneName"]["value"]

            if "synonyms" in g:
                for s in g["synonyms"]:
                    gene_syn.append(s["value"])

        results.append({
            "UniProtID": pid,
            "ProteinName": prot_name,
            "ProteinSynonyms": ", ".join(prot_syn) if prot_syn else None,
            "GeneName": gene_name,
            "GeneSynonyms": ", ".join(gene_syn) if gene_syn else None
        })

    except:
        results.append({
            "UniProtID": pid,
            "ProteinName": None,
            "ProteinSynonyms": None,
            "GeneName": None,
            "GeneSynonyms": None
        })

out_df = pd.DataFrame(results)
out_df.to_csv("protein_final_output.csv", index=False)

files.download("protein_final_output.csv")