# -*- coding: utf-8 -*-
"""String_relation_Validation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nPoxhSvcR_q7YEeItCM7rUFgQa2TlucY
"""

import pandas as pd
import requests
import urllib.parse
from functools import lru_cache
import time

#Input Files and Preprocessing
relations = pd.read_csv("final_ensemble_report_ot.csv")
syn = pd.read_csv("protein_synonyms.csv")

for c in syn.columns:
    syn[c] = syn[c].astype(str)

# Building a Protein Synonym Lookup Dictionary
def get_all_names(row):
    names = [row["ProteinName"], row["GeneName"], row["UniProtID"]]

    # Processing synonyms
    for col in ["ProteinSynonyms", "GeneSynonyms"]:
        if row[col] and row[col] != "nan":
            names.extend([n.strip() for n in row[col].replace("|", ";").split(";")])

    # Cleaning
    names = [n for n in names if n and n.lower() != "nan"]


    return list(dict.fromkeys(names))


lookup = {}
for _, row in syn.iterrows():
    lookup[row["ProteinName"].strip()] = get_all_names(row) #All duplicate and invalid values are removed. This enables flexible matching against STRING, which may recognize proteins under different identifiers.

print(f"Built synonym map for {len(lookup)} proteins.")

#STRING Identifier Resolution (with Caching)
@lru_cache(maxsize=5000)
def find_string_id_cached(name):
    """Cached STRING ID lookup"""
    species = "9606" #Restricting results to human proteins (NCBI Taxonomy ID: 9606)
    url = f"https://string-db.org/api/json/get_string_ids?identifiers={urllib.parse.quote(name)}&species={species}"
    try:
        r = requests.get(url, timeout=5)
        data = r.json()
        if isinstance(data, list) and data:
            return data[0]["stringId"]
    except:
        return None
    return None

#Tries the protein’s primary name, then gene name, then synonyms (up to 8 attempts)
def find_best_string_id(original_name):
    """Try protein name → gene → synonyms (fast, cached)"""
    if original_name in lookup:
        names_tested = 0
        for n in lookup[original_name]:
            sid = find_string_id_cached(n)
            names_tested += 1
            if sid:
                return sid, n
            if names_tested >= 8:
                break
    else:
        sid = find_string_id_cached(original_name)
        if sid:
            return sid, original_name

    return None, None

#STRING Interaction Check
@lru_cache(maxsize=10000)
def check_string_interaction_cached(id1, id2):
    """Cached STRING interaction check"""
    url = f"https://string-db.org/api/json/network?identifiers={id1}%0d{id2}"
    try:
        r = requests.get(url, timeout=5)
        data = r.json()
        if isinstance(data, list) and len(data) > 0:
            score = max([edge.get("score", 0) for edge in data])
            return True, score
        return False, 0
    except:
        return False, 0

# Processing rows
results = []
total = len(relations)

print(f"Processing {total} protein pairs...")

for i, row in relations.iterrows():
    if i % 20 == 0:
        print(f"Progress: {i}/{total}")

    p1 = row["Entity_1"].strip()
    p2 = row["Entity_2"].strip()

    # Get STRING IDs
    id1, used1 = find_best_string_id(p1)
    id2, used2 = find_best_string_id(p2)

    # Check interaction
    if id1 and id2:
        found, score = check_string_interaction_cached(id1, id2)
    else:
        found, score = False, 0

    results.append({
        "Entity_1": p1,
        "Entity_2": p2,
        "Ensemble_Result": row["Ensemble_Result"],
        "BioBERT_Relation": row["BioBERT_Relation"],
        "PubMedBERT_Relation": row["PubMedBERT_Relation"],
        "BioLinkBERT_Relation": row["BioLinkBERT_Relation"],
        "STRING_ID_1": id1,
        "STRING_ID_2": id2,
        "STRING_Found": found,
        "STRING_Score": score,
        "Used_Name_1": used1,
        "Used_Name_2": used2
    })

df_out = pd.DataFrame(results)
df_out.to_csv("STRING_validation_output.csv", index=False)

print("\nFinished! Saved → STRING_validation_output.csv")